export const experienceEvents = [
  {
    slug: "cyborg-party",
    tone: "purple",
    title: "Cyborg Party.",
    titleParts: ["Cyborg", "Party"],
    venue: "INS Land",
    city: "Shanghai",
    date: "May 2026",
    cardImage: "/images/posters/cyborg-party-card.jpg",
    fullImage: "/images/posters/cyborg-party-full.jpg",
    cardTag: "The first fully AI-generated DJ set at a world top-12 club.",
    galleryRatios: ["ar-4-5", "ar-16-9", "ar-3-4", "ar-3-2", "ar-1-1", "ar-3-4", "ar-4-5", "ar-16-9", "ar-3-2"],
    body: [
      "A cyborg night hosted by TheMu at INS Land — ranked in DJ Mag's global top 12 clubs. Robots, brain-computer interfaces, cyborg fashion, and AI on the same dance floor. One of those nights that's hard to explain until you're in it.",
      [
        "Sonicite delivered a fully AI-generated DJ set: every track composed, arranged, and mixed by our own software. The set ran 130–170 BPM across UK Garage, Techno, Trance, and Drum and Bass — with real-time human control on the floor to keep the energy tight. Paired with a live AI VJ visual set, the sound held up in a professional club environment. The most common reaction that night: ",
        { text: "\"This is actually AI?\"", em: true },
      ],
      "The night also featured NFC social networking, AI cocktails, humanoid robots, live hiphop performances, and an AI instrument band — alongside a lineup of tech startups and creative studios.",
    ],
    credits: [
      ["Live Visuals", { text: "Sonara", href: "https://sonara.fm" }, "A browser-based instrument that turns live sound into continuously generated visuals. No rig, no install — just a tab and whatever's playing."],
      ["AI Music & DJ Set", "Xeyea", "Founder of Sonicite. DJ, AIGC creator, and guzheng player who dissolves the line between Chinese instruments and electronic sound."],
      ["Mixing Support", "turtledealer", "Vancouver-born, Manila-based. Underground trap, West Coast bass, and psychedelic trance — transitions you don't see coming."],
      ["MC", "drew.sh", "A developer from Africa who ended up on the mic. Met at a hackerhouse. Turns out he loves hiphop."],
    ],
    partners: [
      "/images/partners/cyborg/themu.png",
      "/images/partners/cyborg/agency.png",
      "/images/partners/cyborg/insland.png",
      "/images/partners/cyborg/bonjour.png",
      "/images/partners/cyborg/zpilot.png",
      "/images/partners/cyborg/fourys.png",
      "/images/partners/cyborg/emotiv.png",
      "/images/partners/cyborg/fam.png",
      "/images/partners/cyborg/hfd.png",
      "/images/partners/cyborg/easybot.png",
      "/images/partners/cyborg/agibar.png",
      "/images/partners/cyborg/roboparty.png",
      { src: "/images/partners/cyborg/breakreal.png", href: "https://www.breakreal.com/" },
    ],
  },
  {
    slug: "art-rave-technology",
    tone: "rose",
    title: "Art Rave Technology.",
    titleParts: ["Art Rave", "Technology"],
    venue: "Palace of Sound",
    city: "Shanghai",
    date: "May 2026",
    cardImage: "/images/posters/art-rave-technology-card.jpg",
    fullImage: "/images/posters/art-rave-technology-full.jpg",
    cardTag: "A creative night where the audience makes the music, then dances to it.",
    galleryRatios: ["ar-4-5", "ar-16-9", "ar-3-4", "ar-3-2", "ar-1-1", "ar-3-4", "ar-4-5", "ar-16-9"],
    body: [
      "A for Art. R for Rave. T for Technology. Untitled Project's first anniversary at Palace of Sound — one of Shanghai's most intimate listening bars — co-presented with Sonicite. A night for artists, designers, musicians, and anyone who makes things: an afternoon workshop, an informal art auction, vibe coding on the floor, and a DJ lineup that ran until 1am.",
      "Sonicite came in on three fronts. In the afternoon, we ran a Vibe workshop — hands-on music-making, open to anyone in the room. For the art auction we provided scene-aware AI-generated background music, shifting with the energy of the space. And for the night, we brought artists from Sonicite's own creative community — each with a distinct sound, all part of how we think about music differently. The music across the night leaned experimental: AI-generated, genre-fluid, pulling from electronic, fusion, and everything in between.",
    ],
    credits: [
      ["Music & Vibe Demo", "Xeyea", "Founder of Sonicite. DJ, AIGC creator, and guzheng player. The AI music across the night was hers — experimental electronic, genre-fluid, drawing from Chinese instrumentation, DnB, UKG, house, jazz, and beyond."],
      ["Workshop", "Cookie", "Co-founder of Sonicite, formerly Tencent, Didi, and Temu. Core member of VibeFriends, an independent developer community. Led the afternoon Vibe workshop."],
      ["DJ", "BluPlanet", "Canadian electronic musician and founder of Project Recordings. Organic House, Progressive House, and Techno — immersive sonic journeys shaped by atmosphere and emotional progression."],
      ["DJ", "Mahakali", "Buddhist practitioner, sound healer, DJ. Dreamy rhythm, minimal beats, and healing soundscapes — music as a path inward."],
      ["DJ", "turtledealer", "Vancouver-born, Manila-based. Underground trap, West Coast bass, and psychedelic trance — transitions you don't see coming."],
      ["Co-presenter", "Untitled Project", "An open art experiment and non-vertical creative collective. They believe everyone is a creator."],
    ],
    partners: [
      "/images/partners/art-rave/palace-of-sound.png",
      { text: "Untitled Project" },
      { text: "VibeFriends" },
      { text: "Project Recordings" },
      { text: "Sonara", href: "https://sonara.fm" },
      { text: "Sonicite Vibe" },
    ],
  },
  {
    slug: "office-rave",
    tone: "amber",
    title: "Office Rave.",
    titleParts: ["Office", "Rave"],
    venue: "Alibaba Center",
    city: "Shanghai",
    date: "June 2026",
    cardImage: "/images/posters/office-rave-card.jpg",
    fullImage: "/images/posters/office-rave-full.jpg",
    cardTag: "The closing night of a global hackerhouse — work all day, rave all night.",
    galleryRatios: ["ar-4-5", "ar-16-9", "ar-3-4", "ar-3-2", "ar-1-1", "ar-3-4", "ar-4-5", "ar-16-9", "ar-3-2", "ar-1-1"],
    body: [
      [
        "MuShanghai was a 28-day pop-up city experiment — 800 builders from 50+ countries, across four themed weeks: AI, biotech, robotics, and culture. Sonicite was its Official Sonic Partner throughout. Office Rave was how the final week ended: Sonicite and ",
        { text: "Sonara", href: "https://sonara.fm" },
        " took over the Town Hall at Alibaba Center for one night — three rooms, five DJs, AI music, and AI cocktails.",
      ],
      "One room was entirely Sonicite's. We opened with a short sharing session — an intro to Sonicite's products and a live demo where everyone could jump in and play with the AI music tools themselves. Then the room kept running on AI-generated music, built and curated with our own software.",
      "The other two rooms were human. Soul, disco, house, funk, techno, trap, trance, Latin grooves — five DJs, two floors, one long night.",
    ],
    credits: [
      ["Live Visuals", { text: "Sonara", href: "https://sonara.fm" }, "A browser-based instrument that turns live sound into continuously generated visuals. No rig, no install — just a tab and whatever's playing."],
      ["AI Cocktails", { text: "Breakreal", href: "https://www.breakreal.com/" }, "The world's first conversational cocktail dispenser. Reads your mood, makes your drink. Featured by Yanko Design and Reuters."],
      ["DJ", "超FUN", "From New York, longtime Burning Man community member. Soul, disco, house, funk, and world grooves — sets built on connection and the shared energy of the dancefloor."],
      ["DJ", "Turtledealer", "Vancouver-born, Manila-based. Underground trap, West Coast bass, and psychedelic trance — transitions you don't see coming."],
      ["DJ", "Taomasta", "From St. Petersburg, based in Shanghai. Over a decade in electronic music culture — sets that balance musical depth with dancefloor intuition."],
      ["DJ", "Lalo", "Spanish DJ moving between Latin House, House, and Techno. Rhythm, groove, and strong progression."],
      ["DJ", "BluPlanet", "Canadian electronic musician and founder of Project Recordings. Organic House, Progressive House, and Techno — immersive sonic journeys shaped by atmosphere and emotional progression."],
      ["AI Music & Product Demo", "Xeyea", "Founder of Sonicite. DJ, AIGC creator, and guzheng player. The AI music room was hers — experimental electronic, genre-fluid, built and curated with Sonicite's own tools."],
    ],
    partners: [
      "/images/partners/office-rave/mushanghai.png",
      { src: "/images/partners/office-rave/sonara.png", href: "https://sonara.fm" },
      { src: "/images/partners/office-rave/breakreal.png", href: "https://www.breakreal.com/" },
    ],
  },
  {
    slug: "rave-coding",
    tone: "blue",
    title: "Rave Coding.",
    titleParts: ["Rave", "Coding"],
    venue: "BiPlace",
    city: "Guangzhou",
    date: "May 2026",
    cardImage: "/images/posters/rave-coding-card.jpg",
    fullImage: "/images/posters/rave-coding-full.jpg",
    cardTag: "A weekend hackathon scored end-to-end with a proper Sonicite soundtrack.",
    galleryRatios: ["ar-4-5", "ar-16-9", "ar-3-4", "ar-3-2", "ar-1-1", "ar-3-4", "ar-4-5", "ar-16-9"],
    body: [
      [
        "Live coding, but make it a rave. GAAi街坊 — a Guangzhou-based party collective using music as a medium for community — hosted the first-ever Rave Coding competition at BiPlace: a mini hackathon where the dancefloor is part of the brief. 20 participants, 4 hours of live development, no fixed topic, no standard answers. The room shifted states every hour — ",
        { text: "Focus, Speed, Minimal, Chaos", em: true },
        " — voted on by the audience in real time. Music, lighting, and rhythm changed with every round. So did everyone's headspace.",
      ],
      "Sonicite provided the soundtrack: AI-generated dub techno, built for deep focus and coded to move with the room. We also brought Vibe to the floor — anyone could jump in, jam, and make something, no experience needed.",
      "The final judging wasn't about completion. It was about whether your project made people want to play.",
    ],
    credits: [
      ["Co-presenter", "GAAi 街坊", "A Guangzhou-based party collective founded in 2025. In Cantonese, 街坊 means neighbor — using music as a medium to make something new in the spaces between people."],
      ["DJ", "Choho", "Active in Guangzhou's music scene. Moves fluidly between UK, Breaks, and Dub — and anywhere else the moment calls for."],
      ["DJ", "Yelen", "Genre-fluid and rhythm-driven. Creates new energy in the room through unexpected collisions between sounds and styles."],
      ["Organizer & DJ", "CharChar", "Founder of Rave Coding, Coffee Rave organizer, AI entrepreneur. Keeps finding ways to put electronic music, social interaction, and live creation in the same room."],
    ],
    partners: [
      "/images/partners/rave-coding/gaai.png",
      "/images/partners/rave-coding/biplace.png",
      "/images/partners/rave-coding/trozk.png",
    ],
  },
];

export const bringItems = [
  ["purple", "AI Music Mixes.", "Custom generative sets that adapt to room, mood, and crowd in real time."],
  ["blue", "Scene-Aware Music.", "Music that responds to who's in the room, what time it is, and what's happening."],
  ["rose", "Immersive Audio-Visual.", "Live sound and generative visuals that move as one — built for the space."],
  ["amber", "Live Music Making.", "Guided live performance with our tools — for any skill level, any crowd."],
  ["purple", "Jam Sessions.", "Open invitations to play together — humans, AI, and whatever instrument shows up."],
  ["blue", "Workshops.", "Hands-on sessions teaching the craft behind AI music — accessible, technical, fun."],
  ["rose", "Real DJ Sets.", "Human DJs deeply embedded in scene culture — vinyl, CDJs, taste, history."],
  ["amber", "Sound Design.", "Bespoke sonic identity for brands, spaces, and moments that need to be heard."],
];

export function getExperienceBySlug(slug) {
  return experienceEvents.find((event) => event.slug === slug);
}
