const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://ioprkugnuswfunqkkvfk.supabase.co";
const experiencesBucketBase = `${supabaseUrl}/storage/v1/object/public/experiences`;

function experienceAsset(folder, filename) {
  return `${experiencesBucketBase}/${folder}/${encodeURIComponent(filename)}`;
}

function experienceImage(folder, filename) {
  return experienceAsset(folder, filename);
}

export const experienceEvents = [
  {
    slug: "cyborg-party",
    tone: "purple",
    title: "Cyborg Party.",
    titleParts: ["Cyborg", "Party"],
    venue: "INS Land",
    city: "上海",
    date: "2026 年 5 月",
    cardImage: "/images/posters/cyborg-party-card.jpg",
    fullImage: "/images/posters/cyborg-party-full.jpg",
    videoSrc: experienceAsset("saibo", "b5114e0e7f73ddef01eb970164923ed9.mp4"),
    cardTag: "在全球 Top 12 club 呈现的第一套全 AI 生成 DJ set。",
    galleryRatios: ["ar-4-5", "ar-16-9", "ar-3-4", "ar-3-2", "ar-1-1", "ar-3-4", "ar-4-5", "ar-16-9", "ar-3-2"],
    galleryImages: [
      "IMG_9635.JPG",
      "IMG_9637.JPG",
      "IMG_9638.JPG",
      "IMG_9643.JPG",
      "222aafadd6fffca1149f433af078185b.jpg",
      "2e059e3a9d66544e8bf7e08195197319.jpg",
      "3d45179a31fac1b427643b5fb1c15ec4.jpg",
      "5478d64e4b39b3e033c13448be5aaa7a.jpg",
      "5fc730148fd27d51332e05897ae64119.jpg",
      "99106730542e362e8dcde71cdf6dfb96.jpg",
      "b04394fb25c4bf2db5ca0c1382c8ee8f.jpg",
      "bef76b3cb88066d72baee5f53f82d864.jpg",
      "c3fb65462e327adf6569410bbd074ca2.jpg",
    ].map((name) => experienceImage("saibo", name)),
    body: [
      "由 TheMu 在 INS Land 主办的 cyborg 之夜。INS Land 位列 DJ Mag 全球 Top 12 club。当机器人、脑机接口、cyborg fashion 和 AI 同时出现在同一个舞池，这就是那种只有身在其中才说得清的夜晚。",
      [
        "Sonicite 呈现了一套全 AI 生成 DJ set：每首歌都由我们的软件完成创作、编排与混音。整套 set 覆盖 130-170 BPM，从 UK Garage、Techno、Trance 到 Drum and Bass，并在现场保留实时人工控制，确保能量始终紧密。配合 live AI VJ 视觉，这套声音经受住了专业 club 环境的检验。当晚最常见的反应是：",
        { text: "\"This is actually AI?\"", em: true },
      ],
      "当晚还包括 NFC 社交、AI 鸡尾酒、人形机器人、live hiphop 表演和 AI 乐器 band，并聚集了一批科技创业团队与创意工作室。",
    ],
    credits: [
      ["现场视觉", { text: "Sonara", href: "https://sonara.fm" }, "一件基于浏览器的乐器，可以把现场声音转化为持续生成的视觉。不需要设备、不需要安装，只要一个标签页和正在播放的声音。"],
      ["AI 音乐 & DJ Set", "Xeyea", "Sonicite 创始人。DJ、AIGC 创作者、古筝演奏者，持续打破中国乐器与电子声音之间的边界。"],
      ["混音支持", "turtledealer", "出生于 Vancouver，常驻 Manila。Underground trap、West Coast bass 与 psychedelic trance，转场总是出乎意料。"],
      ["MC", "drew.sh", "来自非洲的开发者，后来站上了麦克风。我们在 hackerhouse 相识，结果发现他非常热爱 hiphop。"],
    ],
    partners: [
      "/images/partners/cyborg/themu.png",
      "/images/partners/cyborg/agency.png",
      "/images/partners/cyborg/insland.png",
      "/images/partners/cyborg/bonjour.png",
      "/images/partners/cyborg/zpilot.png",
      "/images/partners/cyborg/fourys.png",
      "/images/partners/cyborg/emotiv.png",
      "/images/partners/cyborg/fam.png",
      "/images/partners/cyborg/hfd.png",
      "/images/partners/cyborg/easybot.png",
      "/images/partners/cyborg/agibar.png",
      "/images/partners/cyborg/roboparty.png",
      { src: "/images/partners/cyborg/breakreal.png", href: "https://www.breakreal.com/" },
    ],
  },
  {
    slug: "art-rave-technology",
    tone: "rose",
    title: "Art Rave Technology.",
    titleParts: ["Art Rave", "Technology"],
    venue: "Palace of Sound",
    city: "上海",
    date: "2026 年 5 月",
    cardImage: "/images/posters/art-rave-technology-card.jpg",
    fullImage: "/images/posters/art-rave-technology-full.jpg",
    cardTag: "一个观众先做音乐，再跟着它跳舞的创意夜晚。",
    galleryRatios: ["ar-4-5", "ar-16-9", "ar-3-4", "ar-3-2", "ar-1-1", "ar-3-4", "ar-4-5", "ar-16-9"],
    galleryImages: [
      "028c5b36br8364b7d24a313f38e8b5c5.jpg",
      "1b7f6f3d8l4f84c64e3de0b298abd1b7.jpg",
      "1d0e305fbm1f05cfd4630fe8cb0f72d3.jpg",
      "3c677a0efkf5e022ba875786eaa092d6.jpg",
      "40ec40b55k830aaca3c5498683d8e2aa.jpg",
      "52a29b27di265ec4bb6bdf41e2eb63b6.jpg",
      "5ced3ba4arc9e70ed5307b787ccad052.jpg",
      "6d713b7d2g7c4c87fb4c9363a8f6356f.jpg",
      "7c280f59clf7d108f6b27d2e66e373c2.jpg",
      "8068b80cft3d77144e74c3913770b2a2.jpg",
      "94dc9a1d4o49ccf3ddbe54497c855e95.jpg",
      "be1605f7dq53228783d5686837391f14.jpg",
      "c90cf4f58l53c4fe2ae354eee3d0c0ac.jpg",
      "c9dc55db9t3cb0381f19d5353b9b4f7d.jpg",
      "cbb0b0d6cu796f013a58561257502f94.jpg",
      "d82fc8212g4c999122cc97744230acf1.jpg",
      "f2aa362b4p5804bf58b31b75037284ba.jpg",
      "IMG_9764.JPG",
      "IMG_9765.JPG",
      "IMG_9766.JPG",
      "Weixin Image_20260612011954_939_7317.jpg",
      "Weixin Image_20260612011954_940_7317.jpg",
    ].map((name) => experienceImage("art", name)),
    body: [
      "A for Art. R for Rave. T for Technology. Untitled Project 在 Palace of Sound 的一周年活动，由 Sonicite 联合呈现。Palace of Sound 是上海最亲密的 listening bar 之一。这是一个为艺术家、设计师、音乐人和所有创作者准备的夜晚：下午 workshop、非正式艺术拍卖、舞池里的 vibe coding，以及一直持续到凌晨 1 点的 DJ 阵容。",
      "Sonicite 参与了三个部分。下午，我们举办了 Vibe workshop，让房间里任何人都能上手做音乐。艺术拍卖环节，我们提供了感知场景的 AI 生成背景音乐，随空间能量变化。夜晚，我们带来 Sonicite 自己创意社区里的艺术家，每个人都有鲜明声音，也体现了我们对音乐的不同理解。当晚音乐整体更实验：AI 生成、风格流动，在 electronic、fusion 和更多声音之间穿梭。",
    ],
    credits: [
      ["音乐 & Vibe Demo", "Xeyea", "Sonicite 创始人。DJ、AIGC 创作者、古筝演奏者。当晚 AI 音乐由她创作：实验电子、风格流动，从中国乐器、DnB、UKG、house、jazz 延展到更多声音。"],
      ["Workshop", "Cookie", "Sonicite 联合创始人，曾任职 Tencent、Didi、Temu。独立开发者社区 VibeFriends 核心成员，主持下午的 Vibe workshop。"],
      ["DJ", "BluPlanet", "加拿大电子音乐人，Project Recordings 创始人。Organic House、Progressive House 与 Techno，以氛围和情绪推进塑造沉浸式声音旅程。"],
      ["DJ", "Mahakali", "佛教修行者、声音疗愈师、DJ。梦幻节奏、minimal beats 与疗愈 soundscape，把音乐作为向内的路径。"],
      ["DJ", "turtledealer", "出生于 Vancouver，常驻 Manila。Underground trap、West Coast bass 与 psychedelic trance，转场总是出乎意料。"],
      ["联合呈现", "Untitled Project", "一个开放艺术实验和非垂直创意 collective。他们相信每个人都是创作者。"],
    ],
    partners: [
      "/images/partners/art-rave/palace-of-sound.png",
      { text: "Untitled Project" },
      { text: "VibeFriends" },
      { text: "Project Recordings" },
      { text: "Sonara", href: "https://sonara.fm" },
      { text: "Sonicite Vibe" },
    ],
  },
  {
    slug: "office-rave",
    tone: "amber",
    title: "Office Rave.",
    titleParts: ["Office", "Rave"],
    venue: "Alibaba Center",
    city: "上海",
    date: "2026 年 6 月",
    cardImage: "/images/posters/office-rave-card.jpg",
    fullImage: "/images/posters/office-rave-full.jpg",
    cardTag: "一个全球 hackerhouse 的闭幕夜：白天工作，夜晚 rave。",
    galleryRatios: ["ar-4-5", "ar-16-9", "ar-3-4", "ar-3-2", "ar-1-1", "ar-3-4", "ar-4-5", "ar-16-9", "ar-3-2", "ar-1-1"],
    body: [
      [
        "MuShanghai 是一个持续 28 天的 pop-up city 实验，聚集来自 50 多个国家的 800 位 builder，围绕 AI、biotech、robotics 和 culture 四个主题周展开。Sonicite 是全程 Official Sonic Partner。Office Rave 是最后一周的收尾：Sonicite 和 ",
        { text: "Sonara", href: "https://sonara.fm" },
        " 在 Alibaba Center 的 Town Hall 接管一整晚：三个房间、五位 DJ、AI 音乐和 AI 鸡尾酒。",
      ],
      "其中一个房间完全属于 Sonicite。我们先做了一段简短分享，介绍 Sonicite 产品，并进行现场 demo，让每个人都能直接上手体验 AI 音乐工具。随后，这个房间持续播放由我们自己的软件生成和策划的 AI 音乐。",
      "另外两个房间则由人类 DJ 接管。Soul、disco、house、funk、techno、trap、trance、Latin grooves：五位 DJ，两层楼，一个很长的夜晚。",
    ],
    credits: [
      ["现场视觉", { text: "Sonara", href: "https://sonara.fm" }, "一件基于浏览器的乐器，可以把现场声音转化为持续生成的视觉。不需要设备、不需要安装，只要一个标签页和正在播放的声音。"],
      ["AI 鸡尾酒", { text: "Breakreal", href: "https://www.breakreal.com/" }, "世界首个对话式鸡尾酒出杯机。读取你的情绪，为你调酒。曾被 Yanko Design 和 Reuters 报道。"],
      ["DJ", "超FUN", "来自 New York，长期 Burning Man 社区成员。Soul、disco、house、funk 与 world grooves，set 建立在连接和舞池共享能量之上。"],
      ["DJ", "Turtledealer", "出生于 Vancouver，常驻 Manila。Underground trap、West Coast bass 与 psychedelic trance，转场总是出乎意料。"],
      ["DJ", "Taomasta", "来自 St. Petersburg，常驻上海。十多年电子音乐文化经验，set 在音乐深度与舞池直觉之间取得平衡。"],
      ["DJ", "Lalo", "西班牙 DJ，游走于 Latin House、House 和 Techno。强调 rhythm、groove 与强推进。"],
      ["DJ", "BluPlanet", "加拿大电子音乐人，Project Recordings 创始人。Organic House、Progressive House 与 Techno，以氛围和情绪推进塑造沉浸式声音旅程。"],
      ["AI 音乐 & 产品 Demo", "Xeyea", "Sonicite 创始人。DJ、AIGC 创作者、古筝演奏者。AI 音乐房间由她负责：实验电子、风格流动，并由 Sonicite 自有工具生成和策划。"],
    ],
    partners: [
      "/images/partners/office-rave/mushanghai.png",
      { src: "/images/partners/office-rave/sonara.png", href: "https://sonara.fm" },
      { src: "/images/partners/office-rave/breakreal.png", href: "https://www.breakreal.com/" },
    ],
  },
  {
    slug: "rave-coding",
    tone: "blue",
    title: "Rave Coding.",
    titleParts: ["Rave", "Coding"],
    venue: "BiPlace",
    city: "广州",
    date: "2026 年 5 月",
    cardImage: "/images/posters/rave-coding-card.jpg",
    fullImage: "/images/posters/rave-coding-full.jpg",
    cardTag: "一场从头到尾由 Sonicite 配乐的周末 hackathon。",
    galleryRatios: ["ar-4-5", "ar-16-9", "ar-3-4", "ar-3-2", "ar-1-1", "ar-3-4", "ar-4-5", "ar-16-9"],
    galleryImages: [
      "Weixin Image_20260524211501_327_7818.jpg",
      "Weixin Image_20260525102620_336_7818.jpg",
      "Weixin Image_20260525173157_347_7818.jpg",
      "Weixin Image_20260525173201_348_7818.jpg",
      "Weixin Image_20260525173216_350_7818.jpg",
      "Weixin Image_20260525173218_351_7818.jpg",
      "Weixin Image_20260525173232_354_7818.jpg",
      "Weixin Image_20260614175514_366_7818.jpg",
      "Weixin Image_20260614175520_367_7818.jpg",
    ].map((name) => experienceImage("ravecoding", name)),
    body: [
      [
        "Live coding，但把它变成一场 rave。GAAi街坊是一个来自广州、以音乐作为社区媒介的 party collective。他们在 BiPlace 举办了第一场 Rave Coding competition：一个把舞池也写进 brief 的 mini hackathon。20 位参与者，4 小时现场开发，没有固定题目，也没有标准答案。房间每小时切换一次状态：",
        { text: "Focus, Speed, Minimal, Chaos", em: true },
        "，由观众实时投票决定。每一轮，音乐、灯光和节奏都会改变；每个人的脑内状态也随之改变。",
      ],
      "Sonicite 提供了整场 soundtrack：AI 生成的 dub techno，面向深度专注打造，并会随房间一起移动。我们也把 Vibe 带到现场，任何人都可以加入、jam、做点东西，不需要经验。",
      "最终评审看的不是完成度，而是你的项目是否让人想要玩。",
    ],
    credits: [
      ["联合呈现", "GAAi 街坊", "成立于 2025 年的广州 party collective。在粤语里，街坊意味着邻居。他们用音乐作为媒介，在人与人之间的空间里创造新的东西。"],
      ["DJ", "Choho", "活跃于广州音乐场景。流动于 UK、Breaks、Dub，以及任何当下需要的方向。"],
      ["DJ", "Yelen", "风格流动、节奏驱动。通过声音和风格之间的意外碰撞，为房间制造新的能量。"],
      ["Organizer & DJ", "CharChar", "Rave Coding 创始人，Coffee Rave 主理人，AI entrepreneur。持续把电子音乐、社交互动和现场创作放进同一个房间。"],
    ],
    partners: [
      "/images/partners/rave-coding/gaai.png",
      "/images/partners/rave-coding/biplace.png",
      "/images/partners/rave-coding/trozk.png",
    ],
  },
];

export const bringItems = [
  ["purple", "AI 音乐混音。", "为房间、情绪和人群实时适配的定制生成式 set。"],
  ["blue", "场景感知音乐。", "能回应房间里是谁、现在是什么时间、正在发生什么的音乐。"],
  ["rose", "沉浸式音画。", "现场声音与生成视觉同步移动，为空间而建。"],
  ["amber", "现场音乐创作。", "用我们的工具引导现场表演，适合任何技能水平和任何人群。"],
  ["purple", "Jam Sessions。", "开放邀请大家一起玩：人类、AI，以及任何出现的乐器。"],
  ["blue", "Workshops。", "动手学习 AI 音乐背后的 craft，易进入、有技术含量，也足够好玩。"],
  ["rose", "真实 DJ Sets。", "深度嵌入场景文化的人类 DJ：vinyl、CDJ、审美与历史。"],
  ["amber", "声音设计。", "为品牌、空间和需要被听见的时刻定制声音身份。"],
];

export function getExperienceBySlug(slug) {
  return experienceEvents.find((event) => event.slug === slug);
}
